chore: Adding charge transaction request vaidation
TokoBapak/mock-payment-provider pull request #12
Opened 2023-01-02 05:48 UTC by YogiPristiawan

https://github.com/TokoBapak/mock-payment-provider/issues/3

2023-01-02 06:00 UTC, YogiPristiawan commented
better dipisah package apa jadi satu package presentation ya untuk validationnya? @aldy505

2023-01-02 09:45 UTC, aldy505 requested changes
* presentation layer harusnya cuma convert dari raw input ke business schema. dia nggak berhak buat ngecek length, regex, segala macem dari tiap field. semua itu seharusnya di layer implementasi business.
* kalo validasi dia number atau bukan, nggak perlu pake regex. kalo bisa regex se minimal mungkin dan jangan recompile terus-terusan
* mapping buat raw input ke defined enum di primitive harusnya nggak ada di primitive package, harusnya ada di package yang pake (in this case, harusnya ada di presentation layer)

2023-01-04 00:04 UTC, aldy505 requested changes

2023-01-04 00:04 UTC, aldy505 commented on business/transaction_service/charge_test.go
> +		}
ini harus cek type error sama valuenya. jangan cuma cek kalo nil doang. 

gimana kalo error tapi bukan validation error?

2023-01-04 00:04 UTC, aldy505 commented on presentation/charge_transaction.go
> +		PaymentType:         paymentTypeMap[requestBody.PaymentType],
disini harus validate kalo payment typenya ga valid. 

di business layer cuma validate kalo payment type <= 0, tapi kalo upper limitnya itu 6, artinya masukin input 100 atau 9999 bisa lolos.

2023-01-04 00:04 UTC, aldy505 commented on presentation/charge_transaction.go
> +		TransactionCurrency: currencyMap[requestBody.Transaction.Currency],
ini sama. cara validasinya salah.

2023-01-04 00:04 UTC, aldy505 commented on presentation/charge_transaction.go
> +		if errors.As(err, &business.RequestValidationError{}) {
ga gini cara pake errors.As. isi errornya sebaiknya diliat. jangan di assign ke empty struct.

```suggestion
      var requestValidationError *business.RequestValidationError
		if errors.As(err, &requestValidationError) {
```

abis itu dipake value requestValidationError nya

2023-01-05 14:16 UTC, YogiPristiawan commented on presentation/charge_transaction.go
> +		PaymentType:         paymentTypeMap[requestBody.PaymentType],
Aku asumsinya kalau user nginputinnya salah, value nya bakal 0 sih. makanya di bussiness layer aku cuman cek `PaymentType == 0`

2023-01-05 14:20 UTC, YogiPristiawan commented on presentation/charge_transaction.go
> +		TransactionCurrency: currencyMap[requestBody.Transaction.Currency],
https://github.com/TokoBapak/mock-payment-provider/pull/12#discussion_r1062519763

2023-01-05 14:22 UTC, YogiPristiawan commented on presentation/charge_transaction.go
> +		if errors.As(err, &business.RequestValidationError{}) {
beda ya antara
` var requestValidationError *business.RequestValidationError`
sama
`&business.RequestValidationError`

2023-01-05 14:32 UTC, aldy505 commented on presentation/charge_transaction.go
> +		PaymentType:         paymentTypeMap[requestBody.PaymentType],
yasudah kasih comment aja diatasnya kenapa decide kayak gitu

2023-01-05 14:32 UTC, aldy505 commented on presentation/charge_transaction.go
> +		if errors.As(err, &business.RequestValidationError{}) {
beda. kalo yang pointer ke empty struct itu ya artinya nggak di pake value dari error nya

2023-01-05 16:05 UTC, YogiPristiawan commented on business/transaction_service/charge.go
> +	if ok := regexp.MustCompile(primitive.EmailPattern).Match([]byte(request.Customer.Email)); !ok {
Oh i see. Yg ini lebih berat ya?

2023-01-05 16:24 UTC, yus-ham commented
kenapa ga pakai go library untuk validation, ada ga lib-nya?

2023-01-11 06:16 UTC, closed without merging