chore: handle error 404 and 500 in the charge_presentation
TokoBapak/mock-payment-provider pull request #14
Opened 2023-01-11 13:26 UTC by YogiPristiawan

2023-01-11 13:46 UTC, aldy505 commented
description PR nya harusnya `Closes #4`, biar langsung ke linked ke issue itu

2023-01-11 13:47 UTC, aldy505 requested changes

2023-01-11 13:47 UTC, aldy505 commented on presentation/cancel_transaction.go
>  			// TODO: handle error, return 404
hapus TODO nya

2023-01-11 13:47 UTC, aldy505 commented on presentation/cancel_transaction.go
> +				StatusCode:    http.StatusBadRequest,
StatusCode BadRequest kok kirim StatusNotFound di line 49?

2023-01-11 14:02 UTC, YogiPristiawan commented on presentation/cancel_transaction.go
> +				StatusCode:    http.StatusBadRequest,
wkwk iya salah

2023-01-15 14:14 UTC, aldy505 approved these changes

2023-01-15 14:14 UTC, merged