feat(presentation): proper schema
TokoBapak/mock-payment-provider pull request #17
Opened 2023-04-02 15:03 UTC by aldy505

schema was by Midtrans, all rights reserved

there are some TODOs, others can contribute for it. it's easy enough, I think.

I intend to make this repository as close to Midtrans and how they handle the logic (and the webhook/notification), so when we got a future project that requires integration with Midtrans, we already did save some time developing it.

2023-04-07 09:06 UTC, YogiPristiawan approved these changes

2023-04-14 08:25 UTC, WahidinAji requested changes

2023-04-14 08:25 UTC, WahidinAji commented on presentation/charge_transaction.go
> +			w.WriteHeader(http.StatusInternalServerError)
karena abis kejdian marshar error ga nampilin body. gatau kenapa ini keknya perlu deh, walaupun cuma simple 

w.Write([]byte("internal server error"))


kasihan FE kalo cuma baca header. soale kemarin kejadian di saya FE nya komplen wkwkkwkwkwk ;D

2023-04-14 08:25 UTC, WahidinAji commented on presentation/charge_transaction.go
> +				CountryCode: requestBody.CustomerDetails.BillingAddress.CountryCode,
```suggestion
				FirstName:   requestBody.CustomerDetail.BillingAddress.FirstName,
				LastName:    requestBody.CustomerDetail.BillingAddress.LastName,
				Email:       requestBody.CustomerDetail.BillingAddress.Email,
				Phone:       requestBody.CustomerDetail.BillingAddress.Phone,
				Address:     requestBody.CustomerDetail.BillingAddress.Address,
				PostalCode:  requestBody.CustomerDetail.BillingAddress.PostalCode,
				CountryCode: requestBody.CustomerDetail.BillingAddress.CountryCode,
```

2023-04-14 08:25 UTC, WahidinAji commented on presentation/charge_transaction.go
> +			PhoneNumber: requestBody.CustomerDetails.PhoneNumber,
ini single kan ya? harusnya singular ga? misal `requestBody.CustomerDetail.FirstName` 

```suggestion
			FirstName:   requestBody.CustomerDetail.FirstName,
			LastName:    requestBody.CustomerDetail.LastName,
			Email:       requestBody.CustomerDetail.Email,
			PhoneNumber: requestBody.CustomerDetail.PhoneNumber,
```


soalnya kuliat disini single customer aja kan? https://github.com/TokoBapak/mock-payment-provider/pull/17/files#

2023-04-14 08:25 UTC, WahidinAji commented on presentation/charge_transaction.go
> +			w.WriteHeader(http.StatusInternalServerError)
ini juga, `w.Write([]byte("internal server error")` misal

2023-04-14 08:25 UTC, WahidinAji commented on presentation/charge_transaction.go
> +			w.WriteHeader(http.StatusInternalServerError)
3. w.Write

2023-04-14 08:25 UTC, WahidinAji commented on presentation/charge_transaction.go
> +			w.WriteHeader(http.StatusInternalServerError)
semua lahh pokoknya kwkwkwkwkwwk

2023-04-14 12:02 UTC, aldy505 commented on presentation/charge_transaction.go
> +			w.WriteHeader(http.StatusInternalServerError)
kan yang consume ini sesama backend...

2023-04-16 05:59 UTC, aldy505 commented on presentation/charge_transaction.go
> +				CountryCode: requestBody.CustomerDetails.BillingAddress.CountryCode,
nggak mau. ini kan targetnya mau 1:1 replica sama API nya midtrans. di midtrans dipakenya `CustomerDetails` bukan `CustomerDetail`.

kalo dibikin sesuai kaidah yang wajar, nggak jadi 1:1 replica.

2023-04-16 05:59 UTC, aldy505 commented on presentation/charge_transaction.go
> +			PhoneNumber: requestBody.CustomerDetails.PhoneNumber,
nggak mau. ini kan targetnya mau 1:1 replica sama API nya midtrans. di midtrans dipakenya CustomerDetails bukan CustomerDetail.

kalo dibikin sesuai kaidah yang wajar, nggak jadi 1:1 replica.

2023-04-16 06:01 UTC, aldy505 commented on presentation/charge_transaction.go
> +			w.WriteHeader(http.StatusInternalServerError)
nggak mau. biar sesuai ngikutin midtrans aja.

2023-04-16 06:01 UTC, aldy505 commented on presentation/charge_transaction.go
> +			w.WriteHeader(http.StatusInternalServerError)
nggak mau. biar sesuai ngikutin midtrans aja.

2023-04-16 06:01 UTC, aldy505 commented on presentation/charge_transaction.go
> +			w.WriteHeader(http.StatusInternalServerError)
nggak mau. biar sesuai ngikutin midtrans aja.

2023-04-19 07:03 UTC, merged