pengen beli BMW tapi kok mahal ya :)
TokoBapak/mock-payment-provider pull request #25
Opened 2023-05-17 02:44 UTC by WahidinAji

ya maaf, namanya juga laper. kadang error kadang `signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x51b1f9]`

2023-05-17 02:51 UTC, aldy505 commented
SIGSEV pas kapan?

2023-05-17 03:00 UTC, WahidinAji commented
pas running testnya. tpi itu karena ada yg kurang. sekarng dh ga ada SIGNEV lagi

2023-05-17 14:54 UTC, aldy505 requested changes
Jangan pake mock.

2023-05-17 14:54 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +	mockVirtualAccountRepository := &MockVirtualAccountRepository{}
Sebenernya ini bisa inject langsung struct beneran aja. Toh databasenya cuma sqlite3, gampang create & destroy.

Nanti kalo business function lain yang mau di test, harus modify mock nya. Kalo nggak pake mock, kan yang di modify cuma behavior dan penggunaan benernya.

Kalo ada yang bikin changes di layer repository, dan ternyata implementasinya salah, jadinya ketauan juga, ngga bakal lolos integration test di business layer mereka.

2023-05-17 14:54 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +		t.Logf("result: %v", userId)
Ini cuma test "error atau engga". Seharusnya yang di test itu output nya sesuai atau tidak. Kalo cuma di log gini doang mah... ga usah pake testing sekalian.

2023-05-17 14:54 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
1 menit itu terlalu lama buat unit test. Maximum 30 second, minimum 10 second.

2023-05-17 14:55 UTC, aldy505 commented
Sekalian, codecov result nya sampe hijau dulu kalo bikin PR.

2023-05-19 03:57 UTC, YogiPristiawan commented on business/payment_service/get_details_test.go
> +	mockVirtualAccountRepository := &MockVirtualAccountRepository{}
kira-kira perlu ga sampai bikin test buat make sure business ini manggil function repo A, function repo B. Dipanggil berapa kali, dipanggil pakai parameter apa kek gitu?
atau cukup integration gini aja? nanti db nya pakai db buat testing

2023-05-19 03:58 UTC, YogiPristiawan approved these changes

2023-05-28 03:32 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +	mockVirtualAccountRepository := &MockVirtualAccountRepository{}
Nggak perlu sampe segitunya.

2023-06-12 08:47 UTC, WahidinAji commented
ini nge-cache ato gimana? :/

2023-06-12 08:53 UTC, WahidinAji commented
https://github.com/TokoBapak/mock-payment-provider/blob/service-test-mock-repo/business/payment_service/get_details_test.go#LL123C29-L123C29   


nge-cache kah? @aldy505

2023-06-12 12:37 UTC, aldy505 commented
apanya yang nge cache?

2023-06-15 16:49 UTC, yogip07 commented on business/payment_service/get_details_test.go
>  		vaNumber, err := virtualAccountRepository.CreateOrGetVirtualAccountNumber(ctx, "annedoe@example.com")
Buat bikin state gini apa ga mending bikin helper khusus buat test aja ya? daripada manggil fungsi aslinya?

2023-06-15 16:49 UTC, YogiPristiawan commented on business/payment_service/get_details_test.go
> +	}
Apa ga mending pakai TRUNCATE pak?

2023-06-16 06:18 UTC, WahidinAji commented on business/payment_service/get_details_test.go
>  		vaNumber, err := virtualAccountRepository.CreateOrGetVirtualAccountNumber(ctx, "annedoe@example.com")
ga butuh helper sih. gasuka apalagi buat test segini doang.

2023-06-16 06:19 UTC, WahidinAji commented on business/payment_service/get_details_test.go
> +	}
bisa sih

2023-06-16 06:20 UTC, WahidinAji commented
> apanya yang nge cache?

coba buka link code yg gue kasih sama issue nya ini 
![image](https://github.com/TokoBapak/mock-payment-provider/assets/48281037/21551f9f-2c8f-4464-abf2-d2ed80a16525)

2023-06-19 00:19 UTC, aldy505 commented
> > apanya yang nge cache?
> 
> coba buka link code yg gue kasih sama issue nya ini ![image](https://user-images.githubusercontent.com/48281037/246333278-21551f9f-2c8f-4464-abf2-d2ed80a16525.png)

@WahidinAji oh, ini ignore aja kalo dari CodeFactor

2023-06-19 00:27 UTC, aldy505 requested changes

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +	})
sekalian cek returned error nya apa, pake `errors.Is` atau `errors.As`

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +	})
atau pake `err.Error() == "error string"` juga boleh kalo emang nggak ada type nya

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +	ctx := context.Background()
jangan pake `context.Background()`, pake `context.WithTimeout()` aja biar lebih proper, sekaligus kasih time limit ke setiap test

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +			}
terus-terusan execute delete gini nggak efektif. delete ini biarin di cleanup script di TestMain aja, jangan di setiap function. nanti jadinya nggak bisa jalanin test pake flag `-race`

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +		}
di cek value dari get detail ini apa, jangan cuma cek nggak error doang

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/mark_as_paid_test.go
> +	ctx := context.Background()
jangan pake `context.Background()`

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/mark_as_paid_test.go
> +		})
cek returned error nya

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/mark_as_paid_test.go
> +		}
cek value error nya

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/mark_as_paid_test.go
> +		})
cek returned error nya

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/mark_as_paid_test.go
> +		})
cek returned error nya

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/mark_as_paid_test.go
> +	}
pindahin ke `TestMain`

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/mark_as_paid_test.go
> +	}
kalo ini termasuk setup, harusnya pake `t.Fatal`, karena `t.Error` bakal tetep jalanin test dibawahnya, agak percuma.

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +	}
sama kayak comment sebelumnya, harusnya pake `t.Fatal`, bukan `t.Error`

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +		_, err = virtualAccountRepository.CreateCharge(ctx, vaNumber, orderId, 50000, time.Now().Add(time.Hour))
cek returned value yang jadi underscore ini apa isinya

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +		_, err = emoneyRepository.CreateCharge(ctx, orderId, 50000, time.Now().Add(time.Hour))
cek returned value yang jadi underscore ini apa isinya

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +		_, err = paymentService.GetDetail(ctx, vaNumber)
cek returned value yang jadi underscore ini apa isinya

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +		}
pindahin ke `TestMain`

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +			}
pindahin keluar

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +			}
pindahin keluar

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +			}
pindahin keluar

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +			}
pindahin keluar

2023-06-19 00:27 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +	setupCtx := context.Background()
jangan pake `context.Background()`

2023-06-19 05:53 UTC, WahidinAji commented on business/payment_service/get_details_test.go
> +	ctx := context.Background()
kayak yg sebelumnya? tpi kena error dari CodeFactor itu WKWKWK

2023-06-19 05:54 UTC, WahidinAji commented on business/payment_service/get_details_test.go
> +			}
kena errorcodefaktor kmrin :/

di ignore aja gpp codefactornya?

2023-06-19 05:54 UTC, WahidinAji commented on business/payment_service/get_details_test.go
> +	setupCtx := context.Background()
kena errorcodefaktor kmrin :/

di ignore aja gpp codefactornya?

2023-06-19 05:54 UTC, WahidinAji commented on business/payment_service/get_details_test.go
> +			}
kena errorcodefaktor kmrin :/

di ignore aja gpp codefactornya?

2023-06-19 05:54 UTC, WahidinAji commented on business/payment_service/get_details_test.go
> +			}
kena errorcodefaktor kmrin :/

di ignore aja gpp codefactornya?

2023-06-19 05:54 UTC, WahidinAji commented on business/payment_service/get_details_test.go
> +			}
kena errorcodefaktor kmrin :/

di ignore aja gpp codefactornya?

2023-06-19 11:06 UTC, aldy505 commented on business/payment_service/get_details_test.go
> +	ctx := context.Background()
gapapa

2024-09-09 14:02 UTC, YogiPristiawan approved these changes

2024-09-09 14:14 UTC, aldy505 commented
Ini sebenernya PR ngapain sih, gw udah lupa

2024-09-10 02:43 UTC, WahidinAji commented
lupa dulu ngapain aja, ingetnya cuma benerin test doang

2026-07-10 03:35 UTC, closed without merging